sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.4'
    env: TOXENV=py34
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.5'
    env: TOXENV=lint
  - python: "nightly"
    env: TOXENV=py36

  allow_failures:
  - python: 'nightly'
cache:
  directories:
  - "$HOME/.cache/pip"
install: pip install -U tox coveralls
language: python
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: DQvNzatG4iBuvoKmc+eTL3mJnd+DHa/qJa24w8jVjppDY9A69G/bUsHuQvvMrbWSBTlXykMRqr3jIM9Vch/GK4o4DmMwfvxXfTSU8M9WJzRJ+AI3m05MO/tq3BUyiNp3zNyXJUq2QEVUT5utnYCFWB0CioUrFjD15cVVoyIRhQE=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/pyRFXtrx
